// Server-side full-report prompt builders, used by generate-report-background.js
// (and, dormant, stripe-webhook-background.js). Deeper than the old client-side
// versions since the background function isn't bound by a browser-facing
// response-time ceiling — this is the sole source of truth for the full
// report, so screen and email always show identical, maximally detailed
// content.

// Shared by all six prompts instead of repeated verbatim in each: the
// anti-repetition/anti-filler line exists because a verdict field and its
// paired detail field otherwise tend to say the same thing twice in
// different words, and flags/strengths can drift into generic filler
// ("this is important to consider") once a model runs out of genuinely
// distinct points.
const PREAMBLE = 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Every sentence must add new, specific information: never restate a verdict field inside its paired detail field, never make the same point twice in different words across fields, and never pad with generic filler ("this is important", "it is worth noting", "in today\'s market"). If there is no genuinely new point left to make, write a shorter, sharper sentence rather than a longer generic one. Respond ONLY with valid JSON, no text outside the JSON.';

function projectContext(p) {
  return 'Project: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"';
}

function fullPromptA(p) {
  return PREAMBLE+'\n\n'+projectContext(p)+'\n\nCover ONLY: overall assessment and the creative package (narrative, logline, pitch, originality). NOTHING about budget, market, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"overall_score":7.5,\n"overall_label":"3-5 words",\n"overall_summary":"4-5 sentences covering market positioning, competitive landscape, and realistic outlook",\n"score_benchmark":"one sentence stating the typical score range for comparable first-time/independent projects at this budget and genre, and where this project falls relative to it",\n"biggest_risk":"one detailed sentence",\n"biggest_opportunity":"one detailed sentence",\n"executive_summary":"5-6 sentences: market position, key challenges, recommended path, and what success would realistically look like",\n"creative_score":7,\n"creative_verdict":"one sentence — a sharp headline judgment, not a preview of creative_detail","creative_detail":"7-8 sentences: logline as pitch tool, story structure, character arcs, originality vs current market trends, tone and style considerations",\n"creative_flags":["specific flag 1","specific flag 2","specific flag 3","specific flag 4"],\n"creative_strengths":["specific strength 1","specific strength 2","specific strength 3","specific strength 4"],\n"creative_tips":[{"advice":"specific advice","links":[{"label":"Resource","url":"https://real.url"}]},{"advice":"specific advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"specific advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"specific advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"pitch_assessment":{"thirty_second_pitch":"the ideal 30-second verbal pitch","logline_score":7,"logline_issues":"what is wrong if anything, in detail","logline_improved":"a stronger version","pitch_deck_checklist":["element 1","element 2","element 3","element 4","element 5"]},\n"attachment_strategy":"2-3 sentences on what kind of key crew or cast attachment (director track record, a recognizable actor, an established DP, etc.) would most improve this specific project\'s credibility and financing odds given its stated experience level, and a concrete way to approach securing it",\n"key_crew_recommendations":[{"role":"Director of Photography","profile":"the type of DP experience/portfolio/visual style that would most benefit this specific project","why":"why this hire specifically matters for this project"},{"role":"Editor","profile":"the type of editing background best suited to this genre and pacing","why":"why this hire specifically matters for this project"},{"role":"Composer","profile":"the type of scoring style/experience best suited to this project\'s tone","why":"why this hire specifically matters for this project"},{"role":"Production Designer","profile":"the type of production design experience best suited to this project\'s setting and budget","why":"why this hire specifically matters for this project"}]\n}';
}

function fullPromptB(p) {
  return PREAMBLE+'\n\n'+projectContext(p)+'\n\nCover ONLY: the financial plan (budget realism, funding sources). NOTHING about creative, market, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"financial_score":6,\n"financial_verdict":"one sentence — a sharp headline judgment, not a preview of financial_detail","financial_detail":"7-8 sentences: budget vs scope reality, financing gap, comparable films\' actual budgets, most realistic path to full financing, and timeline expectations",\n"financial_flags":["specific flag 1","specific flag 2","specific flag 3"],\n"financial_strengths":["specific strength 1","specific strength 2","specific strength 3"],\n"financial_tips":[{"advice":"name real fund with amount and eligibility","links":[{"label":"Fund Name","url":"https://real.url"}]},{"advice":"co-production or tax credit advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"alternative financing advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"a fourth concrete financing avenue (e.g. crowdfunding, equity, presales)","links":[{"label":"Name","url":"https://real.url"}]}],\n"financial_action_plan":["30 days: detailed action","60 days: detailed action","90 days: detailed action"],\n"financial_sources":[{"name":"Real Fund Name","type":"Public","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"}],\n"talent_leverage":"3-4 sentences on how the director\'s and any attached cast\'s experience level realistically affects financing odds and festival programmer interest, and what to do to strengthen this",\n"tax_incentive":{"region":"the project\'s production country/region","estimate":"a realistic estimated rebate or tax credit percentage available there for a project like this, or \'Not typically available at this budget level\' if genuinely not applicable","note":"one sentence on how to access it, naming the relevant film commission or tax authority if known, and noting this is an AI estimate to verify locally"},\n"budget_breakdown_guidance":"4-5 sentences giving realistic top-sheet allocation guidance for this specific genre, format and budget level — approximate percentages across above-the-line, below-the-line/production, post-production, and contingency, plus the one or two line items most likely to be underestimated at this budget"\n}';
}

function fullPromptC(p) {
  return PREAMBLE+'\n\n'+projectContext(p)+'\n\nCover ONLY: market and audience (demand, comparables, marketing). NOTHING about creative, budget, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"market_score":7,\n"market_verdict":"one sentence — a sharp headline judgment, not a preview of market_detail","market_detail":"7-8 sentences: current demand, audience behavior, competition, genre trends, and timing considerations",\n"market_flags":["specific market risk 1","specific market risk 2","specific market risk 3"],\n"market_strengths":["specific market advantage 1","specific market advantage 2","specific market advantage 3"],\n"market_tips":[{"advice":"audience positioning advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"market research advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"trend-alignment advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"a fourth concrete market-positioning tip","links":[{"label":"Name","url":"https://real.url"}]}],\n"market_comps":[{"title":"Real Film Title","year":"2023","budget":"budget","result":"specific result with numbers","lesson":"concrete lesson"},{"title":"Real Film Title","year":"2022","budget":"amount","result":"result","lesson":"lesson"},{"title":"Real Film Title","year":"2021","budget":"amount","result":"result","lesson":"lesson"},{"title":"Real Film Title","year":"2023","budget":"amount","result":"result","lesson":"lesson"},{"title":"Real Film Title","year":"2020","budget":"amount","result":"result","lesson":"lesson"}],\n"marketing_strategy":{"overview":"3-4 sentences on marketing approach","pre_release":["action 1","action 2","action 3","action 4"],"social_strategy":"detailed platforms and content approach","community":"how to build community pre-release, in detail","press":"press/journalists/outlets to target, named specifically","budget_estimate":"a realistic marketing/PR budget range for this project\'s scale and how it should be allocated across the above activities"},\n"target_audience_profile":"3-4 sentences giving a specific demographic and psychographic profile of this project\'s realistic core audience — age range, viewing habits, platforms/venues where they can actually be reached — going beyond the general audience category already selected",\n"cautionary_comps":[{"title":"Real Film Title that underperformed or failed to find a distributor","year":"year","budget":"budget","what_went_wrong":"specific, honest reason it underperformed, told plainly","lesson":"one concrete, actionable lesson this project should take from it"},{"title":"Real Film Title","year":"year","budget":"budget","what_went_wrong":"reason","lesson":"lesson"}]\n}';
}

function fullPromptD(p) {
  return PREAMBLE+'\n\n'+projectContext(p)+'\n\nCover ONLY: festival strategy (specific festivals, timing, positioning, development labs). NOTHING about creative, budget, market, distribution.\n\nRespond with exactly this JSON:\n{\n"festival_score":7,\n"festival_verdict":"one sentence — a sharp headline judgment, not a preview of festival_detail","festival_detail":"7-8 sentences: realistic tier, positioning angle, timing strategy, and submission sequencing",\n"festival_flags":["specific positioning risk 1","specific positioning risk 2","specific positioning risk 3"],\n"festival_strengths":["specific festival appeal 1","specific festival appeal 2","specific festival appeal 3"],\n"festival_tips":[{"advice":"Tier 1 festivals worth attempting and why","links":[{"label":"Festival","url":"https://real.submission.url"}]},{"advice":"Tier 2 realistic targets","links":[{"label":"Festival","url":"https://real.submission.url"}]},{"advice":"niche/genre-specific festivals worth targeting","links":[{"label":"Festival","url":"https://real.submission.url"}]},{"advice":"a fourth concrete festival-strategy tip","links":[{"label":"Festival","url":"https://real.submission.url"}]}],\n"festival_action_plan":["30 days: detailed action","60 days: detailed action","90 days: detailed action"],\n"festival_calendar":[{"festival":"Real Festival Name","tier":"A/B/C","deadline":"submission window","fit":"why it fits, in detail","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"}],\n"lab_and_market_opportunities":[{"name":"Real development lab, co-production market or pitch forum (e.g. an established script lab, co-production market, or talent campus)","fit":"why it specifically fits this project\'s stage and needs, in detail","url":"https://real.url"},{"name":"Real opportunity","fit":"fit","url":"https://real.url"},{"name":"Real opportunity","fit":"fit","url":"https://real.url"}]\n}';
}

function fullPromptE(p) {
  return PREAMBLE+'\n\n'+projectContext(p)+'\n\nCover ONLY: distribution and revenue (platforms, pricing, sales agents). NOTHING about creative, budget, market, festivals.\n\nRespond with exactly this JSON:\n{\n"distribution_score":5,\n"distribution_verdict":"one sentence — a sharp headline judgment, not a preview of distribution_detail","distribution_detail":"7-8 sentences: realistic path, acquisition price reality, what needs to happen first, and territory-by-territory considerations",\n"distribution_flags":["specific risk 1","specific risk 2","specific risk 3"],\n"distribution_strengths":["specific advantage 1","specific advantage 2","specific advantage 3"],\n"distribution_tips":[{"advice":"specific platforms with realistic acquisition price range","links":[{"label":"Platform","url":"https://real.url"}]},{"advice":"territory strategy advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"self-distribution or hybrid strategy advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"a fourth concrete distribution tip","links":[{"label":"Name","url":"https://real.url"}]}],\n"distribution_action_plan":["30 days: detailed action","60 days: detailed action","90 days: detailed action"],\n"distribution_platforms":[{"name":"Platform Name","priority":"First","reason":"reason with price range","url":"https://real.url"},{"name":"Platform","priority":"Second","reason":"reason","url":"https://real.url"},{"name":"Platform","priority":"Third","reason":"reason","url":"https://real.url"},{"name":"Platform","priority":"Fourth","reason":"reason","url":"https://real.url"},{"name":"Platform","priority":"Fifth","reason":"reason","url":"https://real.url"}],\n"sales_agents":[{"name":"Real Company Name","focus":"what films they represent","why":"why right for this project, in detail","url":"https://real.url"},{"name":"Real Company","focus":"focus","why":"why","url":"https://real.url"},{"name":"Real Company","focus":"focus","why":"why","url":"https://real.url"},{"name":"Real Company","focus":"focus","why":"why","url":"https://real.url"}],\n"self_distribution_playbook":"3-4 sentences laying out a concrete fallback self-distribution or hybrid (e.g. four-walling plus VOD) plan specific to this project\'s genre and budget, for the scenario where a traditional acquisition doesn\'t materialize"\n}';
}

function fullPromptF(p) {
  return PREAMBLE+'\n\n'+projectContext(p)+'\n\nCover ONLY: revenue projection, international markets, risk assessment, awards strategy and the production roadmap. NOTHING about creative, market, festivals detail, distribution platform detail.\n\nRespond with exactly this JSON:\n{\n"revenue_projection":{"total_realistic":"realistic total revenue range","theatrical":"realistic theatrical revenue or N/A with reason","streaming_svod":"realistic SVOD range","vod_avod":"realistic VOD/AVOD revenue","tv_rights":"realistic TV licensing","international":"realistic international sales total","breakeven_note":"honest, detailed breakeven assessment covering timeline and probability"},\n"international_markets":[{"country":"Country","reason":"specific detailed reason"},{"country":"Country","reason":"reason"},{"country":"Country","reason":"reason"},{"country":"Country","reason":"reason"},{"country":"Country","reason":"reason"}],\n"risk_assessment":{"top_risks":["specific risk 1, with detail","specific risk 2, with detail","specific risk 3, with detail","specific risk 4, with detail"],"mitigation":["mitigation 1, in detail","mitigation 2, in detail","mitigation 3, in detail","mitigation 4, in detail"]},\n"awards_qualification_strategy":"3-4 sentences honestly assessing whether and how this project could realistically pursue an awards-qualifying run (e.g. a qualifying festival or a qualifying theatrical release) given its budget and genre — or, if that is not a realistic goal at this scale, say so plainly and explain why",\n"legal_and_rights_considerations":"3-4 sentences: based on the logline and notes, flag any life-rights or underlying-work clearance this project likely needs (e.g. if it appears based on a true story or an existing work), or state plainly there are no obvious third-party rights issues if it appears to be original; plus a realistic Errors & Omissions (E&O) insurance cost estimate for a project at this budget and format, and when in the production timeline to secure it",\n"roadmap":[{"phase":"Phase 1 — Script & Pitch","action":"detailed, multi-step action with timeline, 2-3 sentences"},{"phase":"Phase 2 — Financing","action":"detailed action naming real funds and realistic timeline, 2-3 sentences"},{"phase":"Phase 3 — Pre-Production & Packaging","action":"detailed action, 2-3 sentences"},{"phase":"Phase 4 — Production & Post","action":"detailed action, 2-3 sentences"},{"phase":"Phase 5 — Festival & Sales","action":"detailed action, 2-3 sentences"}]\n}';
}

function allFullPrompts(p) {
  return [fullPromptA(p), fullPromptB(p), fullPromptC(p), fullPromptD(p), fullPromptE(p), fullPromptF(p)];
}

module.exports = { fullPromptA, fullPromptB, fullPromptC, fullPromptD, fullPromptE, fullPromptF, allFullPrompts };
