// Server-side copies of the 6 full-report prompt builders in index.html
// (fullPromptA..F). Kept in sync manually since the client copies are
// inline JS in a single-file static site with no shared build step.

function fullPromptA(p) {
  return 'You are a senior film market consultant. Write in clear professional English. No markdown, no emoji. Be specific and actionable. Use only real, plausible resources (funds, festivals, platforms, agents) with real URLs. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: overall assessment and the creative package (narrative, logline, pitch, originality). NOTHING about budget, market, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"overall_score":7.5,\n"overall_label":"3-5 words",\n"overall_summary":"2 sentences",\n"biggest_risk":"one sentence",\n"biggest_opportunity":"one sentence",\n"executive_summary":"3 sentences: market position, key challenge, recommended path",\n"creative_score":7,\n"creative_verdict":"one sentence",\n"creative_detail":"3 sentences: logline as pitch tool, story structure, originality vs market",\n"creative_flags":["specific flag"],\n"creative_strengths":["specific strength"],\n"creative_tips":[{"advice":"specific advice","links":[{"label":"Resource","url":"https://real.url"}]},{"advice":"specific advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"pitch_assessment":{"thirty_second_pitch":"the ideal 30-second verbal pitch","logline_score":7,"logline_issues":"what is wrong if anything","logline_improved":"a stronger version","pitch_deck_checklist":["element 1","element 2","element 3"]}\n}';
}

function fullPromptB(p) {
  return 'You are a senior film market consultant. Write in clear professional English. No markdown, no emoji. Be specific and actionable. Use only real, plausible resources (funds, festivals, platforms, agents) with real URLs. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: the financial plan (budget realism, funding sources). NOTHING about creative, market, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"financial_score":6,\n"financial_verdict":"one sentence",\n"financial_detail":"3 sentences: budget vs scope reality, financing gap, most realistic path to full financing",\n"financial_flags":["specific flag"],\n"financial_strengths":["specific strength"],\n"financial_tips":[{"advice":"name real fund with amount and eligibility","links":[{"label":"Fund Name","url":"https://real.url"}]},{"advice":"co-production or tax credit advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"financial_action_plan":["30 days: action","60 days: action","90 days: action"],\n"financial_sources":[{"name":"Real Fund Name","type":"Public","amount":"amount","deadline":"deadline","eligibility":"eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"eligibility","url":"https://real.url"}]\n}';
}

function fullPromptC(p) {
  return 'You are a senior film market consultant. Write in clear professional English. No markdown, no emoji. Be specific and actionable. Use only real, plausible resources (funds, festivals, platforms, agents) with real URLs. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: market and audience (demand, comparables, marketing). NOTHING about creative, budget, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"market_score":7,\n"market_verdict":"one sentence",\n"market_detail":"3 sentences: current demand, audience behavior, competition",\n"market_flags":["specific market risk"],\n"market_strengths":["specific market advantage"],\n"market_tips":[{"advice":"audience positioning advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"market research advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"market_comps":[{"title":"Real Film Title","year":"2023","budget":"budget","result":"specific result with numbers","lesson":"concrete lesson"},{"title":"Real Film Title","year":"2022","budget":"amount","result":"result","lesson":"lesson"}],\n"marketing_strategy":{"overview":"2 sentences on marketing approach","pre_release":["action 1","action 2"],"social_strategy":"platforms and content approach","community":"how to build community pre-release","press":"press/journalists to target"}\n}';
}

function fullPromptD(p) {
  return 'You are a senior film market consultant. Write in clear professional English. No markdown, no emoji. Be specific and actionable. Use only real, plausible resources (funds, festivals, platforms, agents) with real URLs. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: festival strategy (specific festivals, timing, positioning). NOTHING about creative, budget, market, distribution.\n\nRespond with exactly this JSON:\n{\n"festival_score":7,\n"festival_verdict":"one sentence",\n"festival_detail":"3 sentences: realistic tier, positioning angle, timing strategy",\n"festival_flags":["specific positioning risk"],\n"festival_strengths":["specific festival appeal"],\n"festival_tips":[{"advice":"Tier 1 festivals worth attempting and why","links":[{"label":"Festival","url":"https://real.submission.url"}]},{"advice":"Tier 2 realistic targets","links":[{"label":"Festival","url":"https://real.submission.url"}]}],\n"festival_action_plan":["30 days: action","60 days: action","90 days: action"],\n"festival_calendar":[{"festival":"Real Festival Name","tier":"A/B/C","deadline":"submission window","fit":"why it fits","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"}]\n}';
}

function fullPromptE(p) {
  return 'You are a senior film market consultant. Write in clear professional English. No markdown, no emoji. Be specific and actionable. Use only real, plausible resources (funds, festivals, platforms, agents) with real URLs. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: distribution and revenue (platforms, pricing, sales agents). NOTHING about creative, budget, market, festivals.\n\nRespond with exactly this JSON:\n{\n"distribution_score":5,\n"distribution_verdict":"one sentence",\n"distribution_detail":"3 sentences: realistic path, acquisition price reality, what needs to happen first",\n"distribution_flags":["specific risk"],\n"distribution_strengths":["specific advantage"],\n"distribution_tips":[{"advice":"specific platforms with realistic acquisition price range","links":[{"label":"Platform","url":"https://real.url"}]},{"advice":"territory strategy advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"distribution_action_plan":["30 days: action","60 days: action","90 days: action"],\n"distribution_platforms":[{"name":"Platform Name","priority":"First","reason":"reason with price range","url":"https://real.url"},{"name":"Platform","priority":"Second","reason":"reason","url":"https://real.url"}],\n"sales_agents":[{"name":"Real Company Name","focus":"what films they represent","why":"why right for this project","url":"https://real.url"},{"name":"Real Company","focus":"focus","why":"why","url":"https://real.url"}]\n}';
}

function fullPromptF(p) {
  return 'You are a senior film market consultant. Write in clear professional English. No markdown, no emoji. Be specific and actionable. Use only real, plausible resources (funds, festivals, platforms, agents) with real URLs. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: revenue projection, international markets, risk assessment and the production roadmap. NOTHING about creative, market, festivals detail, distribution platform detail.\n\nRespond with exactly this JSON:\n{\n"revenue_projection":{"total_realistic":"realistic total revenue range","theatrical":"realistic theatrical revenue or N/A with reason","streaming_svod":"realistic SVOD range","vod_avod":"realistic VOD/AVOD revenue","tv_rights":"realistic TV licensing","international":"realistic international sales total","breakeven_note":"honest breakeven assessment"},\n"international_markets":[{"country":"Country","reason":"specific reason"},{"country":"Country","reason":"reason"}],\n"risk_assessment":{"top_risks":["specific risk 1","specific risk 2"],"mitigation":["mitigation 1","mitigation 2"]},\n"roadmap":[{"phase":"Phase 1 — Script & Pitch","action":"specific action with timeline"},{"phase":"Phase 2 — Financing","action":"specific action naming real funds"},{"phase":"Phase 3 — Pre-Production & Packaging","action":"specific action"},{"phase":"Phase 4 — Production & Post","action":"specific action"},{"phase":"Phase 5 — Festival & Sales","action":"specific action"}]\n}';
}

function allFullPrompts(p) {
  return [fullPromptA(p), fullPromptB(p), fullPromptC(p), fullPromptD(p), fullPromptE(p), fullPromptF(p)];
}

module.exports = { fullPromptA, fullPromptB, fullPromptC, fullPromptD, fullPromptE, fullPromptF, allFullPrompts };
