// Server-side full-report prompt builders, used only by the background
// webhook (stripe-webhook-background.js). Deeper than the old client-side
// versions since the background function isn't bound by a browser-facing
// response-time ceiling — this is the sole source of truth for the full
// report, so screen and email always show identical, maximally detailed
// content.

function fullPromptA(p) {
  return 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: overall assessment and the creative package (narrative, logline, pitch, originality). NOTHING about budget, market, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"overall_score":7.5,\n"overall_label":"3-5 words",\n"overall_summary":"4-5 sentences covering market positioning, competitive landscape, and realistic outlook",\n"biggest_risk":"one detailed sentence",\n"biggest_opportunity":"one detailed sentence",\n"executive_summary":"5-6 sentences: market position, key challenges, recommended path, and what success would realistically look like",\n"creative_score":7,\n"creative_verdict":"one sentence",\n"creative_detail":"5-6 sentences: logline as pitch tool, story structure, character arcs, originality vs current market trends, tone and style considerations",\n"creative_flags":["specific flag 1","specific flag 2","specific flag 3"],\n"creative_strengths":["specific strength 1","specific strength 2","specific strength 3"],\n"creative_tips":[{"advice":"specific advice","links":[{"label":"Resource","url":"https://real.url"}]},{"advice":"specific advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"specific advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"pitch_assessment":{"thirty_second_pitch":"the ideal 30-second verbal pitch","logline_score":7,"logline_issues":"what is wrong if anything, in detail","logline_improved":"a stronger version","pitch_deck_checklist":["element 1","element 2","element 3","element 4","element 5"]}\n}';
}

function fullPromptB(p) {
  return 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: the financial plan (budget realism, funding sources). NOTHING about creative, market, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"financial_score":6,\n"financial_verdict":"one sentence",\n"financial_detail":"5-6 sentences: budget vs scope reality, financing gap, comparable films\' actual budgets, most realistic path to full financing, and timeline expectations",\n"financial_flags":["specific flag 1","specific flag 2","specific flag 3"],\n"financial_strengths":["specific strength 1","specific strength 2"],\n"financial_tips":[{"advice":"name real fund with amount and eligibility","links":[{"label":"Fund Name","url":"https://real.url"}]},{"advice":"co-production or tax credit advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"alternative financing advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"financial_action_plan":["30 days: detailed action","60 days: detailed action","90 days: detailed action"],\n"financial_sources":[{"name":"Real Fund Name","type":"Public","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"},{"name":"Real Fund","type":"type","amount":"amount","deadline":"deadline","eligibility":"detailed eligibility","url":"https://real.url"}]\n}';
}

function fullPromptC(p) {
  return 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: market and audience (demand, comparables, marketing). NOTHING about creative, budget, festivals, distribution.\n\nRespond with exactly this JSON:\n{\n"market_score":7,\n"market_verdict":"one sentence",\n"market_detail":"5-6 sentences: current demand, audience behavior, competition, genre trends, and timing considerations",\n"market_flags":["specific market risk 1","specific market risk 2"],\n"market_strengths":["specific market advantage 1","specific market advantage 2"],\n"market_tips":[{"advice":"audience positioning advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"market research advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"trend-alignment advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"market_comps":[{"title":"Real Film Title","year":"2023","budget":"budget","result":"specific result with numbers","lesson":"concrete lesson"},{"title":"Real Film Title","year":"2022","budget":"amount","result":"result","lesson":"lesson"},{"title":"Real Film Title","year":"2021","budget":"amount","result":"result","lesson":"lesson"},{"title":"Real Film Title","year":"2023","budget":"amount","result":"result","lesson":"lesson"}],\n"marketing_strategy":{"overview":"3-4 sentences on marketing approach","pre_release":["action 1","action 2","action 3","action 4"],"social_strategy":"detailed platforms and content approach","community":"how to build community pre-release, in detail","press":"press/journalists/outlets to target, named specifically"}\n}';
}

function fullPromptD(p) {
  return 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: festival strategy (specific festivals, timing, positioning). NOTHING about creative, budget, market, distribution.\n\nRespond with exactly this JSON:\n{\n"festival_score":7,\n"festival_verdict":"one sentence",\n"festival_detail":"5-6 sentences: realistic tier, positioning angle, timing strategy, and submission sequencing",\n"festival_flags":["specific positioning risk 1","specific positioning risk 2"],\n"festival_strengths":["specific festival appeal 1","specific festival appeal 2"],\n"festival_tips":[{"advice":"Tier 1 festivals worth attempting and why","links":[{"label":"Festival","url":"https://real.submission.url"}]},{"advice":"Tier 2 realistic targets","links":[{"label":"Festival","url":"https://real.submission.url"}]},{"advice":"niche/genre-specific festivals worth targeting","links":[{"label":"Festival","url":"https://real.submission.url"}]}],\n"festival_action_plan":["30 days: detailed action","60 days: detailed action","90 days: detailed action"],\n"festival_calendar":[{"festival":"Real Festival Name","tier":"A/B/C","deadline":"submission window","fit":"why it fits, in detail","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"},{"festival":"Festival","tier":"tier","deadline":"deadline","fit":"fit","url":"https://real.url"}]\n}';
}

function fullPromptE(p) {
  return 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: distribution and revenue (platforms, pricing, sales agents). NOTHING about creative, budget, market, festivals.\n\nRespond with exactly this JSON:\n{\n"distribution_score":5,\n"distribution_verdict":"one sentence",\n"distribution_detail":"5-6 sentences: realistic path, acquisition price reality, what needs to happen first, and territory-by-territory considerations",\n"distribution_flags":["specific risk 1","specific risk 2"],\n"distribution_strengths":["specific advantage 1","specific advantage 2"],\n"distribution_tips":[{"advice":"specific platforms with realistic acquisition price range","links":[{"label":"Platform","url":"https://real.url"}]},{"advice":"territory strategy advice","links":[{"label":"Name","url":"https://real.url"}]},{"advice":"self-distribution or hybrid strategy advice","links":[{"label":"Name","url":"https://real.url"}]}],\n"distribution_action_plan":["30 days: detailed action","60 days: detailed action","90 days: detailed action"],\n"distribution_platforms":[{"name":"Platform Name","priority":"First","reason":"reason with price range","url":"https://real.url"},{"name":"Platform","priority":"Second","reason":"reason","url":"https://real.url"},{"name":"Platform","priority":"Third","reason":"reason","url":"https://real.url"},{"name":"Platform","priority":"Fourth","reason":"reason","url":"https://real.url"}],\n"sales_agents":[{"name":"Real Company Name","focus":"what films they represent","why":"why right for this project, in detail","url":"https://real.url"},{"name":"Real Company","focus":"focus","why":"why","url":"https://real.url"},{"name":"Real Company","focus":"focus","why":"why","url":"https://real.url"}]\n}';
}

function fullPromptF(p) {
  return 'You are a senior film market consultant writing an in-depth, ultra-detailed report. Write in clear professional English. No markdown, no emoji. Be specific and actionable — favor concrete numbers, named resources, and real URLs over generic advice. Respond ONLY with valid JSON, no text outside the JSON.\n\nProject: Title="'+p.title+'", Logline="'+p.logline+'", Genre="'+p.genre+'", Format="'+p.format+'", Budget="'+p.budget+'", Audience="'+p.audience+'", Distribution="'+p.distrib+'", Country="'+p.country+'", Experience="'+p.experience+'", Notes="'+(p.extra||'None')+'"\n\nCover ONLY: revenue projection, international markets, risk assessment and the production roadmap. NOTHING about creative, market, festivals detail, distribution platform detail.\n\nRespond with exactly this JSON:\n{\n"revenue_projection":{"total_realistic":"realistic total revenue range","theatrical":"realistic theatrical revenue or N/A with reason","streaming_svod":"realistic SVOD range","vod_avod":"realistic VOD/AVOD revenue","tv_rights":"realistic TV licensing","international":"realistic international sales total","breakeven_note":"honest, detailed breakeven assessment covering timeline and probability"},\n"international_markets":[{"country":"Country","reason":"specific detailed reason"},{"country":"Country","reason":"reason"},{"country":"Country","reason":"reason"},{"country":"Country","reason":"reason"}],\n"risk_assessment":{"top_risks":["specific risk 1, with detail","specific risk 2, with detail","specific risk 3, with detail"],"mitigation":["mitigation 1, in detail","mitigation 2, in detail","mitigation 3, in detail"]},\n"roadmap":[{"phase":"Phase 1 — Script & Pitch","action":"detailed, multi-step action with timeline"},{"phase":"Phase 2 — Financing","action":"detailed action naming real funds and realistic timeline"},{"phase":"Phase 3 — Pre-Production & Packaging","action":"detailed action"},{"phase":"Phase 4 — Production & Post","action":"detailed action"},{"phase":"Phase 5 — Festival & Sales","action":"detailed action"}]\n}';
}

function allFullPrompts(p) {
  return [fullPromptA(p), fullPromptB(p), fullPromptC(p), fullPromptD(p), fullPromptE(p), fullPromptF(p)];
}

module.exports = { fullPromptA, fullPromptB, fullPromptC, fullPromptD, fullPromptE, fullPromptF, allFullPrompts };
